import type { CatalogConfig } from "./types";

export const catalog = {
    tabs: [
        { id: "all", label: "catalog.tabs.all" },
        { id: "physical", label: "catalog.tabs.physical" },
        { id: "digital", label: "catalog.tabs.digital" },
        { id: "service", label: "catalog.tabs.service" },
        { id: "tour", label: "catalog.tabs.tour" },
        { id: "hotel", label: "catalog.tabs.hotel" },
        { id: "realEstate", label: "catalog.tabs.realEstate" },
    ],
    sorts: [
        { id: "featured", label: "catalog.sorts.featured" },
        { id: "newest", label: "catalog.sorts.newest" },
        { id: "priceLow", label: "catalog.sorts.priceLow" },
        { id: "priceHigh", label: "catalog.sorts.priceHigh" },
    ],
    listings: [
        {
            id: "smart-living-kit",
            type: "physical",
            name: "catalog.listings.smartLivingKit.name",
            description: "catalog.listings.smartLivingKit.description",
            price: "catalog.listings.smartLivingKit.price",
            meta: "catalog.listings.smartLivingKit.meta",
            badge: "catalog.badges.fastDelivery",
            href: "/catalog/smart-living-kit",
            tone: "primary",
            rating: 4.8,
            priceValue: 129,
            featured: 96,
            createdAt: "2026-06-12",
            search: ["smart", "living", "kit", "home", "office", "physical", "منزل", "منتج"],
        },
        {
            id: "brand-launch-pack",
            type: "digital",
            name: "catalog.listings.brandLaunchPack.name",
            description: "catalog.listings.brandLaunchPack.description",
            price: "catalog.listings.brandLaunchPack.price",
            meta: "catalog.listings.brandLaunchPack.meta",
            badge: "catalog.badges.instantAccess",
            href: "/catalog/brand-launch-pack",
            tone: "violet",
            rating: 4.7,
            priceValue: 49,
            featured: 91,
            createdAt: "2026-06-10",
            search: ["brand", "launch", "digital", "template", "campaign", "رقمي", "علامة"],
        },
        {
            id: "premium-home-cleaning",
            type: "service",
            name: "catalog.listings.premiumHomeCleaning.name",
            description: "catalog.listings.premiumHomeCleaning.description",
            price: "catalog.listings.premiumHomeCleaning.price",
            meta: "catalog.listings.premiumHomeCleaning.meta",
            badge: "catalog.badges.vettedTeams",
            href: "/catalog/premium-home-cleaning",
            tone: "emerald",
            rating: 4.9,
            priceValue: 35,
            featured: 93,
            createdAt: "2026-06-09",
            search: ["cleaning", "home", "service", "team", "booking", "تنظيف", "خدمة"],
        },
        {
            id: "desert-sunset-tour",
            type: "tour",
            name: "catalog.listings.desertSunsetTour.name",
            description: "catalog.listings.desertSunsetTour.description",
            price: "catalog.listings.desertSunsetTour.price",
            meta: "catalog.listings.desertSunsetTour.meta",
            badge: "catalog.badges.pickupIncluded",
            href: "/catalog/desert-sunset-tour",
            tone: "amber",
            rating: 4.8,
            priceValue: 76,
            featured: 89,
            createdAt: "2026-06-08",
            search: ["desert", "sunset", "tour", "ticket", "pickup", "جولة", "تذاكر"],
        },
        {
            id: "city-view-hotel",
            type: "hotel",
            name: "catalog.listings.cityViewHotel.name",
            description: "catalog.listings.cityViewHotel.description",
            price: "catalog.listings.cityViewHotel.price",
            meta: "catalog.listings.cityViewHotel.meta",
            badge: "catalog.badges.instantBooking",
            href: "/catalog/city-view-hotel",
            tone: "sky",
            rating: 4.6,
            priceValue: 118,
            featured: 87,
            createdAt: "2026-06-07",
            search: ["city", "view", "hotel", "stay", "night", "فندق", "إقامة"],
        },
        {
            id: "marina-apartment",
            type: "realEstate",
            name: "catalog.listings.marinaApartment.name",
            description: "catalog.listings.marinaApartment.description",
            price: "catalog.listings.marinaApartment.price",
            meta: "catalog.listings.marinaApartment.meta",
            badge: "catalog.badges.leadReady",
            href: "/catalog/marina-apartment",
            tone: "rose",
            rating: 4.7,
            priceValue: 420000,
            featured: 85,
            createdAt: "2026-06-06",
            search: ["marina", "apartment", "real", "estate", "listing", "عقار", "شقة"],
        },
    ],
} satisfies CatalogConfig;
