import type { ProductConfig } from "./types";

export const product = {
    products: [
        {
            slug: "smart-living-kit",
            type: "physical",
            name: "product.products.smartLivingKit.name",
            summary: "product.products.smartLivingKit.summary",
            description: "product.products.smartLivingKit.description",
            price: "product.products.smartLivingKit.price",
            priceValue: 129,
            badge: "product.products.smartLivingKit.badge",
            cta: "product.cta.physical",
            tone: "primary",
            rating: 4.8,
            highlights: [
                "product.products.smartLivingKit.highlightOne",
                "product.products.smartLivingKit.highlightTwo",
                "product.products.smartLivingKit.highlightThree",
            ],
            facts: [
                { label: "product.facts.delivery", value: "product.products.smartLivingKit.delivery" },
                { label: "product.facts.stock", value: "product.products.smartLivingKit.stock" },
                { label: "product.facts.warranty", value: "product.products.smartLivingKit.warranty" },
            ],
            policies: [
                "product.products.smartLivingKit.policyOne",
                "product.products.smartLivingKit.policyTwo",
            ],
            trust: [
                "product.products.smartLivingKit.trustOne",
                "product.products.smartLivingKit.trustTwo",
            ],
            options: [
                { id: "starter", label: "product.products.smartLivingKit.optionOne" },
                { id: "office", label: "product.products.smartLivingKit.optionTwo" },
            ],
            related: ["brand-launch-pack", "premium-home-cleaning"],
        },
        {
            slug: "brand-launch-pack",
            type: "digital",
            name: "product.products.brandLaunchPack.name",
            summary: "product.products.brandLaunchPack.summary",
            description: "product.products.brandLaunchPack.description",
            price: "product.products.brandLaunchPack.price",
            priceValue: 49,
            badge: "product.products.brandLaunchPack.badge",
            cta: "product.cta.digital",
            tone: "violet",
            rating: 4.7,
            highlights: [
                "product.products.brandLaunchPack.highlightOne",
                "product.products.brandLaunchPack.highlightTwo",
                "product.products.brandLaunchPack.highlightThree",
            ],
            facts: [
                { label: "product.facts.access", value: "product.products.brandLaunchPack.access" },
                { label: "product.facts.fileType", value: "product.products.brandLaunchPack.fileType" },
                { label: "product.facts.license", value: "product.products.brandLaunchPack.license" },
            ],
            policies: [
                "product.products.brandLaunchPack.policyOne",
                "product.products.brandLaunchPack.policyTwo",
            ],
            trust: [
                "product.products.brandLaunchPack.trustOne",
                "product.products.brandLaunchPack.trustTwo",
            ],
            options: [
                { id: "launch", label: "product.products.brandLaunchPack.optionOne" },
                { id: "social", label: "product.products.brandLaunchPack.optionTwo" },
            ],
            related: ["smart-living-kit", "premium-home-cleaning"],
        },
        {
            slug: "premium-home-cleaning",
            type: "service",
            name: "product.products.premiumHomeCleaning.name",
            summary: "product.products.premiumHomeCleaning.summary",
            description: "product.products.premiumHomeCleaning.description",
            price: "product.products.premiumHomeCleaning.price",
            priceValue: 35,
            badge: "product.products.premiumHomeCleaning.badge",
            cta: "product.cta.service",
            tone: "emerald",
            rating: 4.9,
            highlights: [
                "product.products.premiumHomeCleaning.highlightOne",
                "product.products.premiumHomeCleaning.highlightTwo",
                "product.products.premiumHomeCleaning.highlightThree",
            ],
            facts: [
                { label: "product.facts.duration", value: "product.products.premiumHomeCleaning.duration" },
                { label: "product.facts.availability", value: "product.products.premiumHomeCleaning.availability" },
                { label: "product.facts.area", value: "product.products.premiumHomeCleaning.area" },
            ],
            policies: [
                "product.products.premiumHomeCleaning.policyOne",
                "product.products.premiumHomeCleaning.policyTwo",
            ],
            trust: [
                "product.products.premiumHomeCleaning.trustOne",
                "product.products.premiumHomeCleaning.trustTwo",
            ],
            options: [
                { id: "standard", label: "product.products.premiumHomeCleaning.optionOne" },
                { id: "deep", label: "product.products.premiumHomeCleaning.optionTwo" },
            ],
            related: ["smart-living-kit", "desert-sunset-tour"],
        },
        {
            slug: "desert-sunset-tour",
            type: "tour",
            name: "product.products.desertSunsetTour.name",
            summary: "product.products.desertSunsetTour.summary",
            description: "product.products.desertSunsetTour.description",
            price: "product.products.desertSunsetTour.price",
            priceValue: 76,
            badge: "product.products.desertSunsetTour.badge",
            cta: "product.cta.tour",
            tone: "amber",
            rating: 4.8,
            highlights: [
                "product.products.desertSunsetTour.highlightOne",
                "product.products.desertSunsetTour.highlightTwo",
                "product.products.desertSunsetTour.highlightThree",
            ],
            facts: [
                { label: "product.facts.departure", value: "product.products.desertSunsetTour.departure" },
                { label: "product.facts.group", value: "product.products.desertSunsetTour.group" },
                { label: "product.facts.pickup", value: "product.products.desertSunsetTour.pickup" },
            ],
            policies: [
                "product.products.desertSunsetTour.policyOne",
                "product.products.desertSunsetTour.policyTwo",
            ],
            trust: [
                "product.products.desertSunsetTour.trustOne",
                "product.products.desertSunsetTour.trustTwo",
            ],
            options: [
                { id: "standard", label: "product.products.desertSunsetTour.optionOne" },
                { id: "private", label: "product.products.desertSunsetTour.optionTwo" },
            ],
            related: ["city-view-hotel", "premium-home-cleaning"],
        },
        {
            slug: "city-view-hotel",
            type: "hotel",
            name: "product.products.cityViewHotel.name",
            summary: "product.products.cityViewHotel.summary",
            description: "product.products.cityViewHotel.description",
            price: "product.products.cityViewHotel.price",
            priceValue: 118,
            badge: "product.products.cityViewHotel.badge",
            cta: "product.cta.hotel",
            tone: "sky",
            rating: 4.6,
            highlights: [
                "product.products.cityViewHotel.highlightOne",
                "product.products.cityViewHotel.highlightTwo",
                "product.products.cityViewHotel.highlightThree",
            ],
            facts: [
                { label: "product.facts.nights", value: "product.products.cityViewHotel.nights" },
                { label: "product.facts.room", value: "product.products.cityViewHotel.room" },
                { label: "product.facts.cancellation", value: "product.products.cityViewHotel.cancellation" },
            ],
            policies: [
                "product.products.cityViewHotel.policyOne",
                "product.products.cityViewHotel.policyTwo",
            ],
            trust: [
                "product.products.cityViewHotel.trustOne",
                "product.products.cityViewHotel.trustTwo",
            ],
            options: [
                { id: "room", label: "product.products.cityViewHotel.optionOne" },
                { id: "suite", label: "product.products.cityViewHotel.optionTwo" },
            ],
            related: ["desert-sunset-tour", "marina-apartment"],
        },
        {
            slug: "marina-apartment",
            type: "realEstate",
            name: "product.products.marinaApartment.name",
            summary: "product.products.marinaApartment.summary",
            description: "product.products.marinaApartment.description",
            price: "product.products.marinaApartment.price",
            priceValue: 420000,
            badge: "product.products.marinaApartment.badge",
            cta: "product.cta.realEstate",
            tone: "rose",
            rating: 4.7,
            highlights: [
                "product.products.marinaApartment.highlightOne",
                "product.products.marinaApartment.highlightTwo",
                "product.products.marinaApartment.highlightThree",
            ],
            facts: [
                { label: "product.facts.location", value: "product.products.marinaApartment.location" },
                { label: "product.facts.property", value: "product.products.marinaApartment.property" },
                { label: "product.facts.lead", value: "product.products.marinaApartment.lead" },
            ],
            policies: [
                "product.products.marinaApartment.policyOne",
                "product.products.marinaApartment.policyTwo",
            ],
            trust: [
                "product.products.marinaApartment.trustOne",
                "product.products.marinaApartment.trustTwo",
            ],
            options: [
                { id: "callback", label: "product.products.marinaApartment.optionOne" },
                { id: "viewing", label: "product.products.marinaApartment.optionTwo" },
            ],
            related: ["city-view-hotel", "desert-sunset-tour"],
        },
    ],
} satisfies ProductConfig;
