import type { HomeConfig } from "./types";

export const home = {
    hero: {
        eyebrow: "home.hero.eyebrow",
        title: "home.hero.title",
        description: "home.hero.description",
        primaryCta: "home.hero.primaryCta",
        secondaryCta: "home.hero.secondaryCta",
        primaryHref: "/catalog",
        secondaryHref: "#bookings",
    },
    collections: [
        { id: "physical", label: "home.collections.physical", href: "#deals", tone: "primary" },
        { id: "digital", label: "home.collections.digital", href: "#deals", tone: "violet" },
        { id: "services", label: "home.collections.services", href: "#services", tone: "emerald" },
        { id: "bookings", label: "home.collections.bookings", href: "#bookings", tone: "amber" },
        { id: "stays", label: "home.collections.stays", href: "#bookings", tone: "sky" },
        { id: "estate", label: "home.collections.estate", href: "#bookings", tone: "rose" },
    ],
    products: [
        {
            id: "smartKit",
            type: "physical",
            name: "home.products.smartKit.name",
            description: "home.products.smartKit.description",
            price: "home.products.smartKit.price",
            href: "#deals",
            tone: "primary",
        },
        {
            id: "designPack",
            type: "digital",
            name: "home.products.designPack.name",
            description: "home.products.designPack.description",
            price: "home.products.designPack.price",
            href: "#deals",
            tone: "violet",
        },
        {
            id: "homeCleaning",
            type: "service",
            name: "home.products.homeCleaning.name",
            description: "home.products.homeCleaning.description",
            price: "home.products.homeCleaning.price",
            href: "#services",
            tone: "emerald",
        },
        {
            id: "desertTour",
            type: "tour",
            name: "home.products.desertTour.name",
            description: "home.products.desertTour.description",
            price: "home.products.desertTour.price",
            href: "#bookings",
            tone: "amber",
        },
        {
            id: "cityHotel",
            type: "hotel",
            name: "home.products.cityHotel.name",
            description: "home.products.cityHotel.description",
            price: "home.products.cityHotel.price",
            href: "#bookings",
            tone: "sky",
        },
        {
            id: "marinaApartment",
            type: "realEstate",
            name: "home.products.marinaApartment.name",
            description: "home.products.marinaApartment.description",
            price: "home.products.marinaApartment.price",
            href: "#bookings",
            tone: "rose",
        },
    ],
    rails: [
        { id: "featured", title: "home.rails.featured", items: ["smartKit", "designPack"] },
        { id: "services", title: "home.rails.services", items: ["homeCleaning"] },
        { id: "bookings", title: "home.rails.bookings", items: ["desertTour", "cityHotel", "marinaApartment"] },
    ],
    trust: {
        title: "home.trust.title",
        description: "home.trust.description",
        items: [
            { id: "orders", label: "home.trust.orders" },
            { id: "vendors", label: "home.trust.vendors" },
            { id: "support", label: "home.trust.support" },
            { id: "secure", label: "home.trust.secure" },
        ],
    },
    support: {
        eyebrow: "home.support.eyebrow",
        title: "home.support.title",
        description: "home.support.description",
        chat: "home.support.chat",
        ai: "home.support.ai",
        chatHref: "#support",
        aiHref: "#discover",
    },
    footer: {
        title: "home.footer.title",
        description: "home.footer.description",
        cta: "home.footer.cta",
        href: "/catalog",
    },
} satisfies HomeConfig;
